i18n/pt/cosmic_settings.ftl
Adds portuguese (PT-BR) translation
=> Adds portuguese (PT-BR) translation

.github/workflows/ci.yml, Cargo.lock, app/src/pages/desktop/panel/applets.rs, debian/control, pages/desktop/Cargo.toml
Should now build on build server again, so updates can be released
=> Fix cosmic-settings build

Cargo.lock, app/src/pages/desktop/panel/applets.rs, app/src/theme.rs
seems to work well when i test it :)
=> udpate libcosmic

app/src/pages/desktop/wallpaper/widgets.rs
This'll make the wallpaper and color selection responsive to window width adjustments, so there won't be any shrinkage if the window is too narrow.
=> Responsive wallpaper and color selection lists

app/src/app.rs
This was broken in the iced rebase we did recently.
=> Condense navbar if window is too narrow

i18n/it/cosmic_settings.ftl
Updated the Italian translation file to match the content of the English one.
=> i18n(it): Updating Italian language translation

.github/workflows/ci.yml, app/src/pages/desktop/panel/mod.rs, debian/control, flake.nix
This should adress items: 2, 4, and 6 of https://github.com/pop-os/cosmic-panel/issues/51#event-10302004662
It also adds dependencies to the nix flake.
=> Panel settings jammy

i18n/cs/cosmic_settings.ftl
Add support for the Czech translation.
=> i18n(cs): Add Czech translation

Cargo.lock, Cargo.toml, app/src/app.rs, app/src/main.rs, app/src/pages/desktop/options.rs, app/src/pages/desktop/panel/applets_inner.rs, app/src/pages/desktop/panel/inner.rs, app/src/pages/desktop/wallpaper/mod.rs, app/src/pages/desktop/wallpaper/widgets.rs, app/src/pages/input/keyboard/mod.rs, app/src/pages/input/keyboard/shortcuts.rs, app/src/pages/input/mouse.rs, app/src/pages/input/touchpad.rs, app/src/pages/sound.rs, app/src/pages/system/about.rs, app/src/theme.rs, app/src/widget/mod.rs, page/src/binder.rs, pages/desktop/Cargo.toml
Requires https://github.com/pop-os/libcosmic/pull/165
=> refactor: libcosmic rebase with Application API

Cargo.lock, Cargo.toml, app/src/app.rs, app/src/pages/desktop/appearance.rs, app/src/pages/desktop/panel/inner.rs
=> fix(appearance): color picker resize and drag, fixed size, and re-use color picker window if it exists

Cargo.lock, app/Cargo.toml, app/src/pages/desktop/wallpaper/mod.rs, app/src/pages/desktop/wallpaper/widgets.rs, justfile
In the wallpaper settings page:
- Replaces use of the PickList with the Dropdown widget
- Uses the image button widget style for wallpapers and colors
- Uses `static_init` for dynamically caching translated text
=> feat(wallpaper): use dropdown and image button widgets

Cargo.lock, Cargo.toml, README.md, app/Cargo.toml, app/src/app.rs, app/src/pages/desktop/wallpaper/config.rs, app/src/pages/desktop/wallpaper/mod.rs, app/src/pages/desktop/wallpaper/widgets.rs, debian/control, i18n/en/cosmic_settings.ftl, justfile, page/Cargo.toml, page/src/lib.rs, pages/desktop/src/wallpaper.rs
- Adds a file_chooser subscription, and allows pages to create and respond to these dialogs
- Fixes order of display for wallpapers loaded from the current background directory
- Adds buttons for choosing custom colors and images to add, which may be later removed
- Adds ability to change the background folder through the "Recent Folders" options
=> Wallpaper settings improvements

i18n/pl/cosmic_settings.ftl
Added workspace bits and cleaned translation a little bit.
=> Update cosmic_settings.ftl PL translation

i18n/it/cosmic_settings.ftl
Updating Italian translation, after diffing the it file with the en one.
=> i18n(it): Update Italian translation

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/app.rs, app/src/pages/desktop/appearance.rs, app/src/pages/desktop/display/mod.rs, app/src/pages/desktop/panel/applets_inner.rs, app/src/pages/desktop/panel/inner.rs, app/src/pages/desktop/wallpaper/mod.rs, i18n/cs/cosmic_settings.ftl, i18n/en/cosmic_settings.ftl, page/Cargo.toml, pages/desktop/Cargo.toml, pages/desktop/src/wallpaper.rs, pages/system/Cargo.toml, pages/time/src/lib.rs, rust-toolchain.toml
- Updates libcosmic, which had changes to file chooser dialogs and config subscriptions
- Remove stretch feature from the wallpaper settings UI
- Renames Zoom to Fill in wallpaper settings UI
=> Update libcosmic with some wallpaper page improvements

i18n/sv/cosmic_settings.ftl
=> Update cosmic_settings.ftl - Updated Swedish Translation

Cargo.lock, Cargo.toml, app/src/app.rs, app/src/pages/desktop/dock/applets.rs, app/src/pages/desktop/panel/applets_inner.rs, app/src/pages/desktop/panel/inner.rs
this should fix the add applet issue #129 with the libcosmic/iced update.
=> chore: update libcosmic & cleanup

Cargo.lock, Cargo.toml, app/src/pages/desktop/panel/inner.rs, app/src/pages/input/mod.rs, app/src/pages/input/mouse.rs, app/src/pages/input/touchpad.rs
Depends on https://github.com/pop-os/libcosmic/pull/309
=> improv: fix visual style of slider controls

app/src/pages/desktop/appearance.rs, app/src/pages/desktop/dock/applets.rs, app/src/pages/desktop/dock/mod.rs, app/src/pages/desktop/panel/applets_inner.rs, app/src/pages/desktop/panel/mod.rs, app/src/pages/desktop/workspaces.rs
These icons were added in https://github.com/pop-os/cosmic-icons/pull/8
=> fix: update icon names to refer to the icons included in cosmic-icons

i18n/it/cosmic_settings.ftl
Translated everything from scratch and added missing lines
=> Refactor Italian translation

Cargo.lock, Cargo.toml, cosmic-settings/src/app.rs
May fix the occasional mishap where settings and state are not applied or responded to. This affects theme/toolkit changes, dock and panel config changes, and wallpaper state monitoring.
=> feat: use dbus-config to watch for config updates

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/subscription/daytime.rs, cosmic-settings/src/subscription/mod.rs, i18n/en/cosmic_settings.ftl
=> Appearance autoswitch

i18n/pt_BR/cosmic_settings.ftl
Translation update in Brazilian Portuguese, including the addition of new strings and some improvements.
=> i18n(pt-BR): update Brazilian Portuguese translation

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/input/mod.rs
=> feat(input): show touchpad page only if touchpad exists on system

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/system/about.rs, debian/install, justfile, resources/polkit-1/rules.d/cosmic-settings.rules
Requires https://github.com/pop-os/dbus-settings-bindings/pull/13
Closes #217
=> feat(about): editable hostname input

Cargo.lock, cosmic-settings/src/pages/display/mod.rs
- Do not show display options when display is disabled
- On display changes, keep same display active
=> Display settings fixes

cosmic-settings/src/pages/desktop/wallpaper/mod.rs
=> fix: Sync slideshow toggle with cosmic-bg

cosmic-settings/src/pages/desktop/appearance.rs, i18n/en/cosmic_settings.ftl
(Maybe) closes: #208 
Edit: Actually it may be a little different than #208 but it still seems pretty useful.
=> feat: Preview icon themes

cosmic-settings/src/pages/desktop/wallpaper/mod.rs
Closes: #211
The linked issue explains the problem and how to replicate it. Previews for wallpapers in the default folders were not cached which lead to blank previews.
I fixed it by retrieving the current wallpaper from `cosmic-bg` on load. This also fixes a similar issue with blank previews for colors.
=> fix: Properly cache non-custom wallpaper previews

cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/pages/desktop/panel/inner.rs
Reverts pop-os/cosmic-settings#259
=> Revert "fix(panel): use radius_s for panel corner radii"

cosmic-settings/src/pages/desktop/wallpaper/mod.rs
I've encountered intermittent blank previews for custom wallpapers while ~~working on~~ failing to fix a different bug, but after this patch I haven't seen any empty previews at all.
I originally intended to bundle this fix with the other fix, but I haven't made much progress with that bug.
=> fix: Regression leading to blank custom previews

cosmic-settings/src/pages/desktop/panel/inner.rs
Previously, that was another ToString method that was called, that only worked on english system.
This fix #244
=> fix anchor #244

cosmic-settings/src/pages/desktop/appearance.rs
=> Clickable "Experimental settings" list item

cosmic-settings/src/pages/desktop/appearance.rs
=> cleanup: remove frosted toggle

cosmic-settings/src/pages/desktop/appearance.rs
fixes https://github.com/pop-os/cosmic-settings/issues/245
=> fix(appearance): remove extra scrollable from experimental appearance

cosmic-settings/src/pages/desktop/appearance.rs
fixes https://github.com/pop-os/cosmic-settings/issues/277
=> fix(appearance): experimental settings button size

cosmic-settings/src/pages/desktop/workspaces.rs
fixes https://github.com/pop-os/cosmic-settings/issues/281
=> cleanup(workspaces): remove overview thumbnails section

cosmic-settings/src/pages/desktop/dock/applets.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs
requires https://github.com/pop-os/cosmic-applets/pull/427 fixes https://github.com/pop-os/cosmic-settings/issues/290
=> fix(applet): don't force icons to be symbolic

cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/input/keyboard/mod.rs
fixes https://github.com/pop-os/libcosmic/issues/429
=> fix: icon updates

cosmic-settings/src/app.rs
=> fix: Only clear main view on input while searching [issue #300]

cosmic-settings/src/pages/desktop/workspaces.rs
=> chore: change workspace orientation to radio buttons

cosmic-settings/src/pages/desktop/panel/applets_inner.rs
=> fix: update the applet page header to be in the correct location

cosmic-settings/src/pages/desktop/dock/applets.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs
=> fix(dock) add applet button

cosmic-settings/src/pages/input/keyboard/mod.rs
=> fix: Set input list default to "English (US)"

cosmic-settings/src/pages/display/mod.rs
=> fix: Disallow disabling only active display

i18n/pt-BR/cosmic_settings.ftl
pointed out by @otaviobrum in https://github.com/pop-os/cosmic-settings/commit/20a65540020f7ee595002bca30a10d684f453a54#commitcomment-142925968
=> Correct typo in pt-BR translation

i18n/pt-BR/cosmic_settings.ftl
Sentence adjustment for display context.
=> i18n(pt-BR) - Fix typo

i18n/en/cosmic_settings.ftl
There might be different intent, it should switch to dark on sunset, not to light mode.
=> Update cosmic_settings.ftl EN translation sunset

i18n/pl/cosmic_settings.ftl
There might be different intent, it should switch to dark on sunset, not to light mode.
=> Update cosmic_settings.ftl PL Translation sunset

Cargo.toml, cosmic-settings/src/pages/display/mod.rs, rust-toolchain.toml
=> feat(displays): add mirroring and projection options

i18n/en/cosmic_settings.ftl
Since it is possible to switch modes in both directions, let's use a more appropriate title. Complements #222
=> i18n (en): Correct title for the Light/Dark auto-switch setting

i18n/uk/cosmic_settings.ftl
Minor improvements to translation consistency with other COSMIC apps
=> Update Ukrainian translation

i18n/sk/cosmic_settings.ftl
Slovak translations for cosmic-settings have been implemented
=> i18n(sk): Add slovak translations

i18n/en/cosmic_settings.ftl, resources/com.system76.CosmicSettings.Appearance.desktop, resources/com.system76.CosmicSettings.Keyboard.desktop, resources/com.system76.CosmicSettings.Users.desktop, resources/com.system76.CosmicSettings.Workspaces.desktop
Updates some descriptions to match designs, and the comments of desktop entries to match the descriptions.
=> Update desktop entry comments

.github/workflows/ci.yml, Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/sound.rs, debian/control
Requires https://github.com/pop-os/cosmic-settings-subscriptions/pull/1
Adds input and output sound settings, device selection, volume, and mute functions
=> feat: add sound settings page

cosmic-settings/src/pages/sound.rs, debian/install, justfile, resources/com.system76.CosmicSettings.Power.desktop
Adds a desktop entry for Power & Battery and updates the icon of Sound settings.
=> Update desktop entries

cosmic-settings/src/app.rs, cosmic-settings/src/main.rs, debian/install, justfile, resources/com.system76.CosmicSettings.Desktop.desktop, resources/com.system76.CosmicSettings.Input.desktop, resources/com.system76.CosmicSettings.System.desktop, resources/com.system76.CosmicSettings.Time.desktop
Didn't add comments, since I'm not sure what they're supposed to be.
=> Add missing desktop entries

i18n/fr/cosmic_settings.ftl
Hello,
Updated the `cosmic_settings.ftl` translation file to synchronize with the latest changes in the English source version. Changes include:
- Aligned translation strings with the original English version to ensure consistency.
- Added translations for newly introduced strings.
- Corrected outdated translations and adjusted terminology to better match the English context.
Regards,
Roxfr
=> Updated french translation for Cosmic Settings

cosmic-settings/src/pages/display/mod.rs
Scale factors above 200% may be useful on things like 4k 13 inch laptops. So we should provide higher options, even if we don't default to anything above 200%.
The way the dropdown is formatted with scrolling on smaller window sizes could probably be improved. But that will presumably be a libcosmic change, not anything here.
=> display: Add options for DPI scales up to 300%

i18n/th/cosmic_settings.ftl
Add translations of the Thai language.
=> i18n(th): add Thai translations

cosmic-settings/src/pages/input/keyboard/mod.rs
fixes https://github.com/pop-os/cosmic-settings/issues/546
=> Use lv3:rwin_switch as Right Super

.vscode/settings.json, cosmic-settings/src/pages/display/mod.rs
same as #458, but will keep the decimal if there are two rounded values that are equals
=> feat(display): display as integer

i18n/it/cosmic_settings.ftl
Deleted previous pull request to re-check everything. I compared italian strings with english files.
- re-rodered italian strings to match english order and better merge when needed
- added only italian strings, no english strings added
- missing navigation shortcut section, I'll translate it in the next round
Sorry for confusion
=> Italian strings for settings

cosmic-settings/src/pages/display/mod.rs, i18n/en/cosmic_settings.ftl
~~Depends on https://github.com/pop-os/cosmic-comp/pull/779 being merged first.~~ cosmic-comp changes merged.
=> displays: Add X11 scaling settings

i18n/pt/cosmic_settings.ftl
Adds the remaining fields, fixes some translations and organize all the fields in the correct order
=> i18n: Update pt translation

i18n/it/cosmic_settings.ftl
Added missing italian strings
chatgpt aided
human reviewed
=> Updated italian strings

cosmic-settings/src/localize.rs, cosmic-settings/src/pages/desktop/panel/inner.rs, cosmic-settings/src/pages/power/backend/mod.rs, cosmic-settings/src/pages/power/mod.rs, i18n/en/cosmic_settings.ftl, i18n/fr/cosmic_settings.ftl
=> Fix battery remaining time alignment and enhance copy

cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs
- Should close  (#570)
- Tried to show the description and not the command_str  that is used to group shortcuts  with when multiple than one entry is made with the same command_str : e.g. `code`. That is why the new localized_custom_action is using the binding.description and not the command_str and that is why when reading them and try to localise by description i do a unique_by the command_str, otherwise in the search it would show more than one entries due to different description but same command_Str.
e.g. : 
`
(
modifiers: [
Ctrl,
],
key: "e",
description: Some("OPEN VS CODE"),
): Spawn("code"),
(
modifiers: [
Ctrl,
],
key: "r",
description: Some("open custom vs code"),
): Spawn("code"),
`
- Code references:
`localise_action()`: …
=> impl custom shortcuts search, fix#570

cosmic-settings/src/pages/desktop/window_management.rs, i18n/en/cosmic_settings.ftl
=> Add "Disable" option for super key

cosmic-settings/src/pages/desktop/window_management.rs, i18n/en/cosmic_settings.ftl
=> Support setting focus follows cursor delay

cosmic-settings/src/pages/networking/wifi.rs
Makes the WiFi icons in the list use the correct icons, that change depending on signal strength.
=> [WiFi] Adaptive WiFi icons

i18n/hu/cosmic_settings.ftl
=> updated hungarian translations

i18n/sv/cosmic_settings.ftl
I added translation for sections regarding Power & Battery (plus Power Mode) for the Swedish cosmic_settings.ftl-file.
=> Update cosmic_settings.ftl (Swedish)

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/display/arrangement.rs, cosmic-settings/src/pages/networking/vpn/mod.rs, i18n/en/cosmic_settings.ftl
~~Requires https://github.com/pop-os/libcosmic/pull/628~~
=> feat(appearance): add font configuration settings

cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/mod.rs, cosmic-settings/src/pages/desktop/window_management.rs, i18n/en/cosmic_settings.ftl
Closes the first checkbox of https://github.com/pop-os/cosmic-settings/issues/438#issuecomment-2397137366.
=> Add show active window hint button

cosmic-settings/src/pages/power/mod.rs
=> fix battery percentage decimals

Cargo.lock, cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/time/date.rs, cosmic-settings/src/widget/mod.rs
Also includes using spacing variables in more places, and some tweaks to more closely match designs in code (no visual changes), like the 8 padding around icons in `page_list_item`.
=> [Appearance] Indicate currently selected font with checkmark

cosmic-settings/src/pages/desktop/appearance/mod.rs
Makes the syncing of the dark and light modes use an already available function, rather than explicitly doing it inside the message.
Undoes my previous change to the density message for syncing changes between light and dark modes.
=> Clean up density message

i18n/es-419/cosmic-settings.ftl
I had to move some lines around to be 1:1 with the 'en' file.
=> Update cosmic_settings.ftl for 'es-419' to align with 'en' file

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/power/mod.rs, i18n/en/cosmic_settings.ftl
Can set a "Screen Off Time" using https://github.com/pop-os/cosmic-idle (requires https://github.com/pop-os/cosmic-comp/pull/741).
=> Power Savings Settings

Cargo.lock, Cargo.toml
=> fix: color picker

Cargo.lock, cosmic-settings/src/pages/input/keyboard/mod.rs
Updates libcosmic for the sake of consistency with other apps.
Includes minor tweaks to the keyboard popover.
=> Add window borders

Cargo.lock, Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/display/mod.rs, justfile
should fix #774. Ideally the dispatch method could take a timeout too, and the cleanup that exits the process when the main window is closed could be avoided.
=> Fix high cpu memory

Cargo.lock, cosmic-settings/src/app.rs, cosmic-settings/src/pages/display/mod.rs
cosmic-randr hangs if the channel fills up.
=> fix: increase channel size for display service

i18n/da/cosmic_settings.ftl
Add danish translation to Cosminc Settings
=> Add danish translation

cosmic-settings/src/pages/desktop/appearance/icon_themes.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs
The implementations is still not efficient, but this should lay the ground work for a more efficient implementation. I don't think async I/O is really suited for this.
See #752
=> Fix: Only fetch icons on demand.

cosmic-settings/src/pages/input/touchpad.rs
As defined in https://github.com/pop-os/cosmic-comp/blob/master/cosmic-comp-config/src/lib.rs#L45
=> Disable while typing should default to true

Cargo.lock, cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/system.rs, i18n/en/cosmic_settings.ftl
requires https://github.com/pop-os/cosmic-settings-daemon/pull/66
=> chore: add log-out shortcut

i18n/pl/cosmic_settings.ftl
=> Update cosmic_settings.ftl PL Translation logout chore

cosmic-settings/src/pages/system/default_apps.rs
Implement terminal app detection and selection functionality:
- Scan desktop entries for terminal emulators
- Add support for selecting default terminal application
- Retrieve current default terminal using XDG mime associations
- Enable terminal category in dropdown selection
There are still some things that need to be addressed and implemented, such as:
- in the cosmic file, when you right-click on a folder and click on open in terminal, the respective selected terminal will open (I couldn't implement this, because I had no idea how to do it exactly)
- the code may be spaghetti or extremely long, because I'm still learning Rust, so any corrections to the code to shorten it or make it better will be appreciated
- opening files inside the terminal
=> feat: Add terminal application selection to default apps page

i18n/pl/cosmic_settings.ftl
Fixed a typo and consistency of the other thing
=> Update cosmic_settings.ftl PL Translation typos

cosmic-settings/src/app.rs
Resolves https://github.com/pop-os/cosmic-settings/issues/953
=> fix: close context menu when switching pages

i18n/pl/cosmic_settings.ftl
=> Update cosmic_settings.ftl PL translation minor fixes

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/manage_windows.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/move_window.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/nav.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/system.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/tiling.rs, cosmic-settings/src/pages/input/mod.rs, cosmic-settings/src/pages/input/mouse.rs, cosmic-settings/src/pages/input/touchpad.rs, i18n/en/cosmic_settings.ftl
Applies https://github.com/pop-os/cosmic-settings-daemon/pull/71
=> feat: add shortcut for input source switch

i18n/sv/cosmic_settings.ftl
Noticed i had forgot to update to the latest cosmic-settings and translate the magnifer into Swedish while watching @BrodieRobertson s Youtube stream
=> i18n(sv) update Swedish translation

cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/main.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/time/mod.rs, justfile
This also adds a just target `check-features` - which may be good to add to CI?
=> Fix features to improve portability

i18n/nl/cosmic_settings.ftl
add translations for the numlock status,
The translations are lengthy, so I hope they will fit inside the UI elements!
edit:  have made it more similar to KDE plasma's translations, looks much better
=> i18n(nl) translate 'numlock status' to Dutch

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/accessibility/magnifier.rs, cosmic-settings/src/pages/accessibility/mod.rs, cosmic-settings/src/pages/accessibility/wayland.rs, i18n/en/cosmic_settings.ftl
~~Draft while https://github.com/pop-os/cosmic-protocols/pull/56 isn't merged.~~
*Should* be merged after cosmic-comp support, but support in the compositor is optional, the UI can adopt.
=> a11y: screen filters

cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs
fix for https://github.com/pop-os/cosmic-settings/issues/476
=> fix: set theme builder to match theme after theme is changed

cosmic-settings/src/pages/system/users/mod.rs, i18n/en/cosmic_settings.ftl
Full validation for adding a new user, addressing issue https://github.com/pop-os/cosmic-settings/issues/834
Validation rules:
1. All fields required
2. Username needs to be valid based on this https://systemd.io/USER_NAMES/ - implemented with a reg ex so it can be changed as per any specific rules as required
Some layout cleanup included as well.
=> feat: validation for adding a user

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/accessibility/magnifier.rs, cosmic-settings/src/pages/accessibility/mod.rs, cosmic-settings/src/pages/networking/wifi.rs, cosmic-settings/src/pages/sound.rs, i18n/en/cosmic_settings.ftl
requires https://github.com/pop-os/cosmic-settings-daemon/pull/77 & https://github.com/pop-os/cosmic-settings-subscriptions/pull/8
fixes #653
=> Feat mono sound

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/localize.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/manage_windows.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/move_window.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/nav.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/system.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/tiling.rs, cosmic-settings/src/pages/system/about.rs, i18n/en/cosmic_settings.ftl, page/Cargo.toml, page/src/binder.rs, page/src/insert.rs, page/src/lib.rs, page/src/section.rs, pages/wallpapers/Cargo.toml
=> improv(keyboard): shortcuts UI improvements

Cargo.lock, cosmic-settings/src/pages/accessibility/magnifier.rs, i18n/en/cosmic_settings.ftl
~~Draft until https://github.com/pop-os/cosmic-comp/pull/1322 is merged.~~
=> a11y/zoom: new settings

cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/main.rs, cosmic-settings/src/pages/applications/mod.rs, cosmic-settings/src/pages/mod.rs, justfile
=> Add feature for legacy applications page

i18n/sv/cosmic_settings.ftl
More accessibility translations into Swedish
=> Update cosmic_settings.ftl (sv translation)

cosmic-settings/src/pages/desktop/wallpaper/config.rs
NixOS is not a Linux distribution that is compliant with the "File Hierarchy System." The top-level directory `/usr` does not exist on NixOS. So on NixOS, we won't find any backgrounds in the `/usr/share/backgrounds/` directory.
Instead, what one usually finds in `/usr/share` on FHS-compliant distributions, on NixOS, it is found in the
`/run/current-system/sw/share` directory.
So, check if we are on NixOS or a NixOS-like distribution by checking the `/etc/os-release` file. If we are on such distribution, use the `/run/current-system/sw/share/backgrounds/` directory. Otherwise, use the `/usr/share/backgrounds/` directory for getting system backgrounds.
=> change `default_folder` path of system backgrounds based on distribution

i18n/pl/cosmic_settings.ftl
=> Update cosmic_settings.ftl PL translation X11 shortcuts, accesibility

i18n/pl/cosmic_settings.ftl
Meaning of the modified words:
`Powiększ` - "make it bigger"
`Zmniejsz` - "make it smaller"
=> Fix an error in Polish translation

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/applications/startup_apps.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/dock/applets.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/manage_windows.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/move_window.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/nav.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/system.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/tiling.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/time/date.rs, cosmic-settings/src/pages/time/region.rs, page/src/binder.rs, page/src/insert.rs, page/src/lib.rs, page/src/section.rs
@git-f0x This should be what you need.
Also updates fontdb, as needed by cosmic-text.
=> feat: make ContextDrawer model accessible to pages

cosmic-settings/src/app.rs, cosmic-settings/src/pages/applications/startup_apps.rs, cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/display/mod.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/time/date.rs, cosmic-settings/src/pages/time/region.rs
Followup to #1136.
This updates Settings to use the newer ContextDrawer API.
=> Use ContextDrawer model in pages

cosmic-settings/src/pages/system/users/mod.rs
This ensures the appropriate hashing method is used based on the /etc/login.defs file. This is tested and working in Pop and Arch for user creation and password updating.
This is a followup to the discussion here: https://github.com/pop-os/cosmic-settings/pull/1129#discussion_r2052474934
=> fix: use appropriate hashing method for passwords

cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs
Copied the code from DeleteBinding.
Previously overwriting default keybinds left them still working.
=> Disable default keybinds when they are modified.

i18n/pl/cosmic_settings.ftl
Added a couple of missing translations, tweaked some of the wording, and fixed a couple mistakes
=> i18n(pl) Update and fix Polish translation

i18n/sv/cosmic_settings.ftl
=> Update cosmic_settings.ftl (Swedish translation new fork)

i18n/es/cosmic_settings.ftl
Updated the translation and reorganized the file to match the english one.
=> i18n(es) Updated the spanish translation to match the english version

cosmic-settings/src/pages/display/mod.rs
Closes: #1190
RandR may revert or not apply invalid mode changes. The revert dialog shouldn't show in these cases because there isn't anything to revert.
=> fix(display): Don't show revert dialog if RandR reset invalid mode

cosmic-settings/src/pages/bluetooth/mod.rs
This PR ensures that all adapters become undiscoverable when leaving the bluetooth page or when quitting the app entirely.
=> improve(bluetooth): ensure adapters are undiscoverable on leave

cosmic-settings/src/pages/time/date.rs
Default military_time and first_day_of_week to locale's preferred values
=> feat(date): default to locale's preferred date settings

Cargo.lock, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, pages/wallpapers/Cargo.toml, pages/wallpapers/src/lib.rs
This PR enhances the `Wallpapers` section in Settings by recursively discovering the backgrounds directory.
To maintain performance, the search depth is limited to 3 levels.
=> feat: recursively discover wallpapers

i18n/es-419/cosmic-settings.ftl, i18n/hu/cosmic_settings.ftl, i18n/it/cosmic_settings.ftl, i18n/nl/cosmic_settings.ftl, i18n/pt/cosmic_settings.ftl, i18n/sv/cosmic_settings.ftl
Fix various duplicates and fix curly brackets errors
=> i18n: fix duplicates and curly brackets

i18n/hu/cosmic_settings.ftl, i18n/it/cosmic_settings.ftl, i18n/pt/cosmic_settings.ftl
=> i18n: fix window-management-appearance

cosmic-settings/src/pages/networking/wifi.rs
Enable connections to open WiFi:s
=> fix(wifi): enable connection to open wifis

i18n/pl/cosmic_settings.ftl
Added poweroff, improved consistency
=> Update cosmic_settings.ftl PL Translation poweroff

i18n/en/cosmic_settings.ftl, i18n/hu/cosmic_settings.ftl, resources/com.system76.CosmicSettings.Input.desktop
=> Update Hungarian translations

i18n/da/cosmic_settings.ftl
Update danish translation for Cosmic Settings.
=> i18n(da): Update danish translation

i18n/pl/cosmic_settings.ftl
=> Update cosmic_settings.ftl PL Translation Amplification

cosmic-settings/src/pages/power/mod.rs
It is not valid to have multiple devices with the same device path. When a new device connection is received, check for an existing `ConnectedDevice` with the same path and replace it with the new `ConnectedDevice`. Append only if no match was found.
Closes #1377
=> fix(power): connected devices may contain duplicates

cosmic-settings/src/pages/power/backend/mod.rs, cosmic-settings/src/pages/power/mod.rs
Adds subscriptions for watching battery status changes for the system and all connected devices with batteries.
Closes #1317
=> feat(power): subscribe to battery events

Cargo.lock, cosmic-settings/src/pages/desktop/panel/inner.rs
cosmic-settings PR that pairs with https://github.com/pop-os/cosmic-panel/pull/452
=> fix: add unhide_delay for panels

cosmic-settings/src/pages/time/region.rs
this fixes so that time settings are not changed on auth failure etc.
=> fix(region): dont update time settings on set_locale failure

cosmic-settings/src/pages/desktop/panel/applets_inner.rs
Addresses https://github.com/pop-os/cosmic-settings/issues/1456
=> fix: case sensitivity in applet search

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs
fixes https://github.com/pop-os/cosmic-settings/issues/1462 and fixes https://github.com/pop-os/cosmic-settings/issues/1449
=> fix: allow no modifier for function keys
