scss/search.scss, scss/title.scss, src/widgets/search_bar.rs
- Search button no longer shifts to the right when clicked
- Navigation bar is slightly taller, no longer changing height when the search bar is hidden/revealed.
- Clicking the search button now focuses the cursor in the text box, saving precious milliseconds.
=> Reduced search bar motion. Search button focuses cursor.

Cargo.lock, Cargo.toml, src/main.rs, src/sections/wifi/visible_networks.rs, src/task.rs
Something like this should work effectively for handling GTK events in Rust without the need for much reference counting.
- Uses an event loop in a `glib::MainContext::default()` spawned local future for handling events to the WiFi widget and managing all WiFi-related state.
- Sends events using a `tokio::sync::mpsc::UnboundedSender` so it doesn't block widget signals
- AP info stored in a `SlotMap` so they can be referenced by an ID across events.
- Added dummy dialog to respond to configure signals
- Convenience function `task::spawn_local` for spawning tasks locally on GLib.
- `task::spawn` for spawning tasks in the background on Tokio.
=> WiFi scanning improvements

Cargo.lock, pages/system/Cargo.lock, pages/system/Cargo.toml, pages/system/src/lib.rs
I noticed it was showing in GB, when it should probably use GiB. This handles that, and also shows in TiB, MiB, etc. as needed.
=> Use `byte_unit` to display memory and disk space

app/src/pages/desktop/panel/applets.rs, app/src/pages/desktop/panel/mod.rs
I had changed my Panel config's name to be "panel" at some point instead of "Panel", but it should be "Panel" too
=> fix: Panel typo

app/src/pages/desktop/panel/mod.rs
I'm not sure what would be the best default here, but I've gone with 4 for now.
=> fix: set the margin of the panel when setting anchor gap

app/src/pages/desktop/panel/inner.rs
This fixes a potential panic if the dock or panel configs are not defined.
=> Return early from panel PageInner::update function if no panel_config

app/src/pages/desktop/wallpaper/config.rs, app/src/pages/desktop/wallpaper/mod.rs, app/src/pages/desktop/wallpaper/widgets.rs, i18n/cs/cosmic_settings.ftl, i18n/en/cosmic_settings.ftl, i18n/it/cosmic_settings.ftl, i18n/ru/cosmic_settings.ftl, i18n/sr-Cyrl/cosmic_settings.ftl, i18n/sr-Latn/cosmic_settings.ftl, i18n/tr/cosmic_settings.ftl, i18n/zh-TW/cosmic_settings.ftl, pages/desktop/src/wallpaper.rs, resources/com.system76.CosmicSettings.desktop
- Added "Open new folder" dropdown menu list option
- Replaces behavior when adding images
- Adds a new dialog for choosing a folder
- Fixed custom images disappearing when switching to the system wallpaper option
- Changed "System backgrounds" option to "Wallpapers"
- Changed text referencing "background" to "wallpaper"
- Added symbolic file icon when a recent folder is selected
- Custom images and the "Add image" button are hidden when showing a recent folder
- Fixed possible duplicates in the wallpaper background selection view
- Culls missing paths from config if config contained paths that no longer exists
=> Wallpaper improvements and fixes

app/src/pages/desktop/wallpaper/mod.rs
- Switched to `Url::to_file_path` over `Url::path` due to URL encoding of paths breaking file paths.
- Also added some code documentation here for some of the undocumented types, fields, and variants.
=> fix(wallpaper): unable to add folders and images with spaces

pages/system/src/about.rs
- neither `greetd` nor `cosmic-greeter` nor `cosmic-session` set DESKTOP_SESSION, which seems to be a legacy/deprecated variable now, which means the "Desktop environment" field is visually empty
- so this PR updates the detection of desktop environment to check for newer XDG_(SESSION|CURRENT)_DESKTOP variables first
- I've confirmed that this fixes the "Desktop environment" field when running in a COSMIC session started from `cosmic-greeter`, and it also continues to work in COSMIC and GNOME sessions when started from `gdm` (which does set the DESKTOP_SESSION variable)
=> fix: thorough detection of desktop environment

Cargo.lock, Cargo.toml, app/Cargo.toml, app/src/app.rs, app/src/main.rs, app/src/pages/desktop/appearance.rs, app/src/pages/desktop/display/arrangement.rs, app/src/pages/desktop/display/graphics.rs, app/src/pages/desktop/display/mod.rs, app/src/pages/desktop/display/text.rs, app/src/pages/desktop/mod.rs, app/src/pages/desktop/wallpaper/mod.rs, app/src/pages/mod.rs, app/src/pages/sound.rs, app/src/pages/system/about.rs, app/src/pages/time/date.rs, app/src/theme.rs, app/src/widget/mod.rs, debian/control, i18n/en/cosmic_settings.ftl, justfile, page/Cargo.toml, page/src/binder.rs, page/src/lib.rs, pages/desktop/Cargo.toml, pages/system/Cargo.toml, pages/system/src/about.rs, pages/time/Cargo.toml
Requires https://github.com/pop-os/cosmic-randr/pull/7
Adds the display settings page, which contains controls for configuring displays. This includes a custom display arrangement widget for positioning widgets on a virtual grid. The widget ensures that displays are attached to an adjacent display, with guided alignment at certain points.
=> Display settings page

app/src/pages/desktop/wallpaper/mod.rs
- The Fill and Fit to Screen options in the interface were flipped
- Changing between outputs will no longer flip wallpapers, and will also select that wallpaper's active background
All that remains is to improve handling of toggling the slideshow feature.
=> Wallpaper settings improvements

app/src/app.rs, app/src/pages/display/arrangement.rs, app/src/pages/display/mod.rs, page/src/section.rs
- Adjust size of output based on scale
- Show the display arrangement section only when there's more than one display
- Adjust the display arrangement scrollable to be centered after updates
- Use `cosmic::theme` spacing values around interface
`cosmic-randr` will be patched to automatically adjust positions after display scale changes
=> Display page improvements

pages/system/src/about.rs
This PR fixes the two issues brought up in #164 with how memory and disk capacity are displayed:
- The values are now displayed in binary units (GiB, TiB, etc.) instead of decimal/metric units (GB, TB, etc.)
- The values are now rounded to two decimal places
| Before | After |
| --- | --- |
| ![Memory: 33.555890176 GB, Disk Capacity: 13.800913174528 TB](https://github.com/pop-os/cosmic-settings/assets/76545554/24cfe401-a0f7-4e68-8b0d-0569841e8cfa) | ![Memory: 31.25 GiB, Disk Capacity: 12.55 TiB](https://github.com/pop-os/cosmic-settings/assets/76545554/8a6558b2-2b3e-468d-b60f-66d1f046154c) |
Previously this page was displaying metric/decimal units, which is why the capacity seemed overstated.
I also rounded to two decimals places, instead of truncating, as recommended by the original …
=> system/about: Improve memory and disk capacity display

resources/com.system76.CosmicSettings.About.desktop, resources/com.system76.CosmicSettings.Appearance.desktop, resources/com.system76.CosmicSettings.DateTime.desktop, resources/com.system76.CosmicSettings.Desktop.desktop, resources/com.system76.CosmicSettings.Displays.desktop, resources/com.system76.CosmicSettings.Firmware.desktop, resources/com.system76.CosmicSettings.Keyboard.desktop, resources/com.system76.CosmicSettings.Mouse.desktop, resources/com.system76.CosmicSettings.Notifications.desktop, resources/com.system76.CosmicSettings.RegionLanguage.desktop, resources/com.system76.CosmicSettings.Sound.desktop, resources/com.system76.CosmicSettings.Touchpad.desktop, resources/com.system76.CosmicSettings.Users.desktop, resources/com.system76.CosmicSettings.Wallpaper.desktop, resources/com.system76.CosmicSettings.Workspaces.desktop, scripts/cargo.just
This will prevent them from displaying in the app library, while preserving them in the launcher.
Closes #214
=> fix: disable display of settings page entries

cosmic-settings/src/pages/desktop/appearance.rs
According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), `XDG_DATA_DIRS` should default to `/usr/local/share/:/usr/share/` if empty.
I've found that the variable is inconsistently set across environments. I couldn't find any reason as to why it's sometimes unset, but it seems like defaulting to the above is expected behavior.
Besides that, I switched the code that manually split the env arg with a function in the standard library that does the same.
=> Fallback to default XDG_DATA_DIRS for icon search

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/mod.rs, cosmic-settings/src/pages/mod.rs, debian/control, i18n/en/cosmic_settings.ftl, page/src/binder.rs, page/src/lib.rs
=> Keyboard settings page

cosmic-settings/src/pages/desktop/appearance.rs
Fixes the dark theme color palette being applied when selecting theme options on the light theme, and light theme colors being applied to the dark theme when switching from the light theme.
=> fix(appearance): theme mode settings not applied when changing theme mode

cosmic-settings/src/pages/system/about.rs
Fixes #216.
Removed `sections.insert(related())` since it's short and looks messy when commented.
Didn't change i18n files, since they can be used later.
Edit: This probably doesn't do what it's supposed to, since more extensive changes are required to keep "Get support" while removing Related settings. Should the Related section be renamed to Support, with appropriate edits in i18n? Otherwise, feel free to close this.
=> Remove "Related settings" from Settings > About

cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/pages/desktop/panel/inner.rs
This PR makes the Dock and Top Panel follow the corner radius specified by the theme.
@wash2
=> fix(appearance): use same theme border radius for dock and panel.

cosmic-settings/src/pages/input/keyboard/mod.rs
fixes https://github.com/pop-os/cosmic-settings/issues/284
=> fix(input): remove extra scrollable from context menu

cosmic-settings/src/app.rs, cosmic-settings/src/main.rs
This is a temporary solution to force the settings app to close when the display background service hangs. Maybe it should eventually be refactored to run in a separate process? Sorta fixes https://github.com/pop-os/cosmic-settings/issues/303
=> fix: exit on close

cosmic-settings/src/pages/input/keyboard/mod.rs
=> fix: Sort keyboard layouts

cosmic-settings/src/pages/input/keyboard/mod.rs, i18n/en/cosmic_settings.ftl
Hi !
This PR adds a section to the keyboard settings to change repeat rate and delay.
Slider breakpoints have been inserted at the current default values (600 for delay, 25 for rate).
Depends on [cosmic-comp #496](https://github.com/pop-os/cosmic-comp/pull/496).
The sliders extremities aren't exactly aligned because the "Long" and "Fast" words don't have the exact same width, but I guess this is something that will be fixed when the slider notches labels have been implemented and used here.
I've tried to chose the min and max values of each slider so that the default lies in the middle and also so that users cannot make their keyboard unusable by setting an insane repeat rate or close-to-zero repeat delay.
Thanks !
=> feat: add typing assist section with keyboard repeat rate and delay

cosmic-settings/src/pages/display/arrangement.rs
I don't know what the reason was to multiply the max dimensions by 1.25, but it causes the displays to not be centered properly in the arrangement section for me.
This is what it looks like for me when multiplying by 1.25
This is what it looks like when I remove it
=> Fix centering displays in arrangement

cosmic-settings/src/pages/display/mod.rs
When changing the position, scale, orientation, etc. of a display, reload the output configuration from cosmic-randr. This will make sure the UI is up to date with the changes. It also re-centers the displays in the arrangement.
This fixes #298.
It also fixes the issues described in the first  comment of #296. However, adjusting the display scaling can still cause displays to overlap or spread apart. Solving this problem for all possible display arrangements is non-trivial. At least with this change, you'll notice the problem in the UI immediately without having to go to another settings page and back.
=> Reload display config after randr change

cosmic-settings/src/pages/display/mod.rs, i18n/en/cosmic_settings.ftl
Resolves #365 
This feature adds a confirmation prompt with a countdown once a setting is changed. The settings will automatically revert if the timer runs to 0.
The dialog will appear for orientation or scale changes, and the enabling/disabling of a display. It is currently not implemented for display position, resolution, nor refresh rate changes. For any setting change in which someone wishes to add the dialog, I have added a macro to make implementing the dialog simple.
I am not sure if the design choice I made for closing the dialog after timeout was a good one. I made a Widget which just sends a continuous stream of a single message. If that was a good choice, then I am not sure if it is okay to be a private struct at the bottom of the file, or if it should be public or have its own …
=> Adding dialog to confirm display changes.

cosmic-settings/src/pages/input/mouse.rs, cosmic-settings/src/pages/input/touchpad.rs
Display input speed (mouse + touchpad) range as [1,100]. The minimum and maximum values of the selectable range should result in the same value being passed to libinput as before.
Fixes #285
=> Display input speed (mouse + touchpad) range as [1,100]

Cargo.lock, cosmic-settings/src/pages/desktop/wallpaper/widgets.rs
Closes: #348
This fix can be simplified by deriving `PartialOrd` for [cosmic_settings_wallpaper::Color](https://github.com/pop-os/cosmic-bg/blob/2259f5ac81099a8215d5ff69cba1ec0d1fd850d1/config/src/lib.rs#L101).  Let me know if I should open a PR for that followed by revising this PR to be a bit simpler.
=> fix: Duplicate color wallpaper previews

pages/wallpapers/src/lib.rs
Fixes #391, alongside with pop-os/cosmic-bg#43.
Also adds a missing gradient present in the designs.
=> [Wallpaper] Fix gradient direction

Cargo.toml, cosmic-settings/src/pages/display/arrangement.rs, cosmic-settings/src/pages/display/mod.rs
Improves the experience when dragging displays around the display arrangement widget
=> feat(displays): pan left and right when dragging displays to edge

cosmic-settings/src/pages/desktop/appearance.rs
This tweaks the spacing values in the icon theme selection grid, to more closely match designs.
Before: 
After:
The slightly horrible `theme.space_xs() + 1` is required for the grid to fit evenly (equal padding on both sides) in the ContextDrawer. This could maybe be improved in the future with flexible spacing, so that it always fits evenly (e.g. when the window is shrunk horizontally).
A minor difference from the designs is that the column_spacing is space_xs/12, instead of 10 (I couldn't make it so that it fits evenly with 10).
=> Improve icon theme spacing

i18n/uk/cosmic_settings.ftl
1. Use "[one]" plural category instead of "[1]" to cover multiple digits (1, 21, 31, 41, 51, 61, 71, 81, 101, 1001, …) in Ukrainian language.  
Source: https://cldr.unicode.org/index/cldr-spec/plural-rules  
2. Use plural forms for variables with "minutes" and "seconds"
3. Improve string consistency with Ukrainian translations of "cosmic-applets" and "cosmic-files"
=>  Update Ukrainian translation

cosmic-settings/src/app.rs
This allows the flex layout to shrink the scrollable and make room for the title. Otherwise the title might disappear when the window height is small. fixes #449
=> fix: make sub page view scrollable height Fill

cosmic-settings/src/app.rs, cosmic-settings/src/pages/input/mod.rs, cosmic-settings/src/pages/power/mod.rs, cosmic-settings/src/pages/time/mod.rs, i18n/en/cosmic_settings.ftl
Also rearranges the fluent file to match the order of pages, for easier translation (let me know if the other i18n files should be rearranged as well, as part of this), and updates the icons of the Power & Battery, Input Devices and Time & Language NavBar pages (requires pop-os/cosmic-icons#15).
=> Match NavBar item order to designs

cosmic-settings/src/pages/sound.rs
Please see the issue #515 and the following video for the fix for more:
[flex-row-adaptive-width-slider.webm](https://github.com/user-attachments/assets/13491480-04f7-43bc-9783-1df1a9138177)
=> (fix) Flex row and adaptive width slider in sound settings. (fix #515)

cosmic-settings/src/pages/time/date.rs, i18n/en/cosmic_settings.ftl
Closes: #494
Requires: pop-os/cosmic-applets#609
=> feat(time): Option to display seconds on the clock applet

cosmic-settings/src/pages/desktop/mod.rs, cosmic-settings/src/pages/desktop/window_management.rs, cosmic-settings/src/pages/display/mod.rs, cosmic-settings/src/pages/input/touchpad.rs, i18n/en/cosmic_settings.ftl, i18n/sr-Cyrl/cosmic_settings.ftl, i18n/sr-Latn/cosmic_settings.ftl
Should close #294.
Also fixes the order of the window control button toggles on the Window management page, as well as fix the messy indentation for Night Light comments I left a while back.
A minor issue is that the text doesn't update in the the running instance of Settings when the workspace layout is changed, so relaunching Settings is required to get the correct text after changing the workspace layout. Help on this would be appreciated.
=> [Touchpad] Match page to design

pages/system/src/about.rs
The disk capacity is  wrong when a single file system is mounted multiple times,  like:
```
/dev/mapper/root on /nix type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=263,subvol=/@nix)
/dev/mapper/root on /root type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=258,subvol=/@root)
/dev/mapper/root on /.snapshots type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=264,subvol=/@snapshots)
/dev/mapper/root on /home type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=257,subvol=/@home)
/dev/mapper/root on /srv type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=259,subvol=/@srv)
/dev/mapper/root on /var/cache type btrfs (rw,relatime,compress=zstd:5,ssd,space_cache=v2,subvolid=260,subvol=/@cache)
/dev/mapper/root …
```
=> fix: deduplicate disks when calc disk capacity

cosmic-settings/src/pages/desktop/workspaces.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/touchpad.rs, cosmic-settings/src/pages/power/mod.rs
This is likely temporary until a more global change to make entire list items with a radio or toggle clickable (including the internal list item padding; similar to the highest level subpage buttons, e.g. Appearance), but considerably enhances the radio list item UX for now.
Couldn't quite figure out how to do the same for toggle list items, but their UX is slightly better than radio buttons before this change, regardless.
=> Make entire length of radio list items clickable

cosmic-settings/src/pages/input/keyboard/shortcuts/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/nav.rs
Closes #512.
Adds the Switch to workspace [number] entries to the Navigation section.
=> [Shortcuts] Add switch to workspace

cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/pages/desktop/dock/mod.rs, cosmic-settings/src/pages/desktop/panel/inner.rs, cosmic-settings/src/pages/desktop/panel/mod.rs
- Opacity slider updates on the dock and panel pages will be written after a delay
- Theme builder configs are now set explicitly on message updates
- Themes are only built if a theme builder config set reported that the config changed
- Moved file export serialization into command
- Update dock and panel border radius on a tokio thread
- Build new themes from the theme builder on tokio thread
- Theme builder changes shared between modes are now synced on a tokio thread
-  Improved command handling in the appearance settings page
Closes #474
=> perf(desktop): reduce disk usage when reading and writing configs

cosmic-settings/src/widget/mod.rs
Adjusted to match a 100% scaled image from the designs.
Also removes the fixed height, which caused text to be cut off at smaller window widths.
=> fix(page_list_item): match padding to design

cosmic-settings/src/app.rs
This adds the `cosmic-settings network` command line option, which was missing (noticed while testing network applet settings button).
=> Add network subcommand

Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/widget/mod.rs, i18n/en/cosmic_settings.ftl
This adds the 3 interface density options from the designs: Comfortable, Compact and Spacious.
Should be tested alongside pop-os/libcosmic#603.
=> [Appearance] Interface density

cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance.rs, cosmic-settings/src/pages/networking/mod.rs, cosmic-settings/src/widget/mod.rs, debian/install, i18n/en/cosmic_settings.ftl, justfile, resources/com.system76.CosmicSettings.Network.desktop
Adds an `info` argument to `page_list_item` that displays next to the arrow. `min_height` wasn't used for the container because it includes padding, so I added 8px vertical padding to a fixed size (20) component, to set it to 36 to match designs.
It would probably be better if padding around the icons could be set, since that would eliminate the need for a few `.padding` calls.
It has minor text wrapping issues, in that the text on the left doesn't wrap reliably if it doesn't have a description (not sure how to fix).
Should the "Connected", etc. text display only when there are multiple adapters of a type, rather than always?
Also includes various minor fixes.
Edit: Fixes #627 (order checked with Maria).
=> [Networking] Match page list item to design

cosmic-settings/src/pages/input/keyboard/mod.rs, i18n/en/cosmic_settings.ftl
Adds option to remap different keys to caps lock like super, escape or backspace as well as swap caps lock and escape.
=> [Keyboard]: option to remap keys to caps lock

i18n/sv/cosmic_settings.ftl
Removed some duplicated English text in the 'Power & Battery'-section, plus added translation in the 'Date & Time'-section of the Swedish 'COSMIC Settings'-file.
=> Update cosmic_settings.ftl (Swedish translation for 'Time & Date')

cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/input/keyboard/mod.rs
This is to reset the related CosmicTk configs to the defaults.
Also fixes the styling of the extended input sources toggle.
Not entirely sure about the second commit, but it seems to work/behave the same as roundness.
=> Add density to reset to default

cosmic-settings/src/app.rs
Fix #657 
* There is only one message received  per display that from that we need to create two messages for both dock and panel internal data model. 
* Didn't check for outputRemoved but i guess i would need to unplug one of my monitors to receive that type of message.
=> fix(dock): Dock configurable per display.

cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs
Fix #575 
* Clear shortcut context and close the context_drawer where the panics happen in an empty slab/array when deleting the last keybind of a shortcut.
* This is a solution where it may be acceptable if we consider that there is no point for a user to delete the last keybind of a shortcut instead of editing it, without wanting  to delete the shortcut as a whole.
* A totally different "user journey" would be to although you have deleted everything in memory and config/fs, to open the Add shortcut context-drawer by having the previous deleted command and description ,if any, populated, but this fix would be a lot more difficult.
[screen-capture.webm](https://github.com/user-attachments/assets/6340c5fc-fbbc-40a8-a888-80bbfabfa848)
=> fix(shortcuts): Prevent panic when deleting the last keybind of a custom shortcut.

cosmic-settings/src/pages/bluetooth/agent.rs, cosmic-settings/src/pages/bluetooth/mod.rs, cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/icon_themes.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/networking/wired.rs, cosmic-settings/src/pages/power/backend/mod.rs, cosmic-settings/src/pages/sound.rs, cosmic-settings/src/pages/time/date.rs, cosmic-settings/src/widget/mod.rs, i18n/en/cosmic_settings.ftl
- Moves font selection to searchable context views
- Removes weight, stretch, and style options
- Setting a font now sets the font for GTK applications too
- Moves icon themes code to icon_themes module
Closes #683
=> improv(appearance): move fonts into context view

cosmic-settings/src/pages/input/keyboard/mod.rs
The ability to remap the caps lock key was recently added but it wasn't possible to remap it to act as an extra control key. This commit makes that possible.
This is especially useful to reduce stress on the pinky finger when using control heavy applications like Emacs.
=> Add the ability to remap caps lock to control

cosmic-settings/src/pages/power/backend/mod.rs
Fixes #561.
Changes:
Before:
After:
Wrongfully using upower.on_battery (https://upower.freedesktop.org/docs/UPower.html) property instead of upower.device.state (https://upower.freedesktop.org/docs/Device.html) . The first one indicates whether it is a PC or laptop not if it is charging. The sibling properties of the object is LidIsClose :
I also found what KDE and lxqt is doing and what is using to derive this info:
1) https://github.com/lxqt/lxqt-powermanagement/issues/295#issuecomment-1015934354
2) https://github.com/KDE/solid/blob/master/src/solid/devices/frontend/battery.h#L201-L208 ( main KDE librarry abstration used for both)
3) An unrelated issue about the icon and this exact info into the main upower repo:  https://gitlab.freedesktop.org/upower/upower/-/merge_requests/20
4) …
=> fix(power): Fix battery state / charge  devices info.

cosmic-settings/src/pages/sound.rs
Fixes #712 . I was working on #711  and observed this, haven't figured out #711 yet though seems to be something different.
I double-checked with the almost same code of the cosmic-applet-audio here: https://github.com/pop-os/cosmic-applets/blob/master/cosmic-applet-audio/src/lib.rs#L381-L392
Edit: Just noticed in the applet we have a **64ms** delay whilst on settings **500ms**, which one of the two is correct?
There will be a significant noticeable difference with these changes applied between the two.
I think the 500ms feels kind of "laggy" when noticing cosmic-osd  whilst the 64ms seems like it is  applied almost "real-time" in my opinion. I could change the settings one in this PR if you have something in mind.
=> fix(sound): Apply sound volume debounce.

Cargo.lock, Cargo.toml, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/main.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/mod.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/display/mod.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/system/mod.rs, cosmic-settings/src/pages/time/mod.rs, cosmic-settings/src/subscription/mod.rs, pages/wallpapers/Cargo.toml
This enables cosmic-settings to be built with minimal capabilities for other OS's (namely the appearance page).
=> Make pages requiring OS features configurable

cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/networking/vpn/mod.rs, cosmic-settings/src/pages/power/mod.rs, cosmic-settings/src/pages/system/about.rs
- Dynamically calls `on_enter` and `on_leave` as sections are displayed in search
- Updates a few pages to use the new abortable tasks feature in iced for their `on_enter` tasks
=> feat: dynamically load pages when their sections are searched

Cargo.lock, cosmic-settings/src/pages/power/mod.rs, i18n/en/cosmic_settings.ftl
This is a minor improvement to not show a non-applicable option on e.g. desktops.
I assumed that suspend on AC works the same on laptops and desktops, so I just added a separate fluent key to not mention "plugged in" on systems without a battery (since that's the only state they can be in).
Also fixed a minor text mismatch between the designs and implementation.
=> [Power] Only show suspend on battery power if the system has a battery

Cargo.lock, cosmic-settings/src/app.rs, cosmic-settings/src/pages/bluetooth/mod.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/dock/applets.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/networking/vpn/mod.rs, cosmic-settings/src/pages/networking/wifi.rs, cosmic-settings/src/pages/networking/wired.rs, cosmic-settings/src/pages/power/mod.rs, cosmic-settings/src/widget/mod.rs
This makes the min width horizontal padding "match" the designs with `@space_s`. It doesn't really match them, since all apps have 8 padding around them, so the previous value was technically more correct.
But since the padding around apps will likely be removed (so that the scrollbar is closer to the edge), it might be better to use the value from the designs (though the dynamic padding is more complex in the designs, depending on window width, etc...).
So this technically fixes #511, at least when not using Compact density (slight clipping with the scrollbar).
Initially wanted to try to fix [this issue](https://github.com/pop-os/cosmic-epoch/issues/1202), but wasn't able to, so I got carried away with the minor code cleanup. :)
=> fix: condensed padding

Cargo.lock, cosmic-settings/src/pages/desktop/panel/inner.rs
This PR ensures that when the user sets a panel applet size override, it will be reset if the user decides to change the size via the settings UI.
this is useful since we don't have any UI setting to change the applet size override
=> reset size overrides on panel size change

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/bluetooth/mod.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/display/mod.rs, cosmic-settings/src/pages/input/keyboard/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/networking/vpn/mod.rs, cosmic-settings/src/pages/networking/wifi.rs, cosmic-settings/src/pages/networking/wired.rs, cosmic-settings/src/pages/time/mod.rs, cosmic-settings/src/pages/time/region.rs, cosmic-settings/src/widget/mod.rs, i18n/en/cosmic_settings.ftl, page/src/lib.rs
=> feat: add Region & Language page

cosmic-settings/src/pages/desktop/appearance/mod.rs
Fixed the behavior of the spin button for the appearance settings.
Changed the order of the active hint spin button to the following:  
```rs
cosmic::widget::spin_button(
page.theme_builder.active_hint.to_string(),
page.theme_builder.active_hint,
1,
0,
500,
Message::WindowHintSize,
),
```  
It was changed from:  
```rs
cosmic::widget::spin_button(
page.theme_builder.active_hint.to_string(),
1,
page.theme.active_hint,
0,
500,
Message::WindowHintSize,
),
```  
The reason for the change is because the the step and value were swapped making both the active_hint spin button and the gaps spin button have unintended behaviors.
=> Fixed spin button behavior in desktop->appearance->mod.rs

cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/dock/applets.rs
fixes https://github.com/pop-os/cosmic-epoch/issues/1202
=> fix: show add applet context drawer

Cargo.lock, cosmic-settings/src/app.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/system/default_apps.rs, debian/install, i18n/en/cosmic_settings.ftl, justfile, resources/com.system76.CosmicSettings.DefaultApps.desktop
This adds a desktop entry for default apps, and matches the description and icon of its page list item to designs.
Also includes a minor padding fix for the Add applets context drawer, and removes the (likely accidental) additions to the NavBar in #789.
=> [Default apps] Add desktop entry

Cargo.lock, Cargo.toml, cosmic-settings/src/pages/display/mod.rs, i18n/de/cosmic_settings.ftl, i18n/en/cosmic_settings.ftl
Draft until `cosmic-randr` changes are merged, so we don't have the patched dependency.
But this shouldn't regress as old `cosmic-randr` versions should never report `adaptive_sync_support`. So already ready for review.
=> Adaptive VRR support

Cargo.lock, Cargo.toml, cosmic-settings/src/app.rs, cosmic-settings/src/pages/bluetooth/mod.rs, cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, cosmic-settings/src/pages/desktop/panel/inner.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/display/mod.rs, cosmic-settings/src/pages/display/night_light.rs, cosmic-settings/src/pages/networking/vpn/mod.rs, cosmic-settings/src/pages/networking/wifi.rs, cosmic-settings/src/pages/networking/wired.rs, cosmic-settings/src/pages/time/date.rs, cosmic-settings/src/pages/time/region.rs, cosmic-settings/src/widget/mod.rs
This makes the applet name centered if it doesn't have a description, same as on the main applet page.
I don't have multiple displays, so I didn't test the Display page changes, but they should match designs (provided the designs I'm looking at are up-to-date).
Edit: Or should the padding for display arrangement be removed (I can't test so I'm not sure what that looks like), since it doesn't seem to be the same in all places in the designs?
=> [Applets] Center applet text without a description in the applets context drawer

Cargo.lock, cosmic-settings/src/pages/bluetooth/mod.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs, i18n/en/cosmic_settings.ftl
This removes extra horizontal padding from the applet list, which caused misalignment.
Didn't notice it with the previous PR.
Edit: The second commit should fix #797. I think the logic is correct (or more the removal of it), but have no idea how to test.
Should also fix #708 on the Bluetooth page, since it seems `settings::item_row` causes the issue, while `settings::item::builder` works properly.
=> [Bluetooth] Remove settings cog next to Bluetooth toggle

cosmic-settings/src/pages/desktop/appearance/mod.rs
Working on fixing [issue #805](https://github.com/pop-os/cosmic-settings/issues/805)
Updated the appearance page’s gap min to reflect the theme_builder.active_hint value instead of the default theme.active_hint value. I still need to test the change in this commit before merging.
=> Updated appearance gap min

i18n/pl/cosmic_settings.ftl
In "Automatically hide panel" and "automatically hide dock"  in Polish both "panel" and "dock" are translated as panel.
Described in issue 
[BUG] Wrong translation of "Automatically hide dock" in Polish #878
=> Fix polish translation of automatically hide dock

cosmic-settings/src/pages/bluetooth/backend.rs, cosmic-settings/src/pages/bluetooth/mod.rs
The list of nearby bluetooth devices without an alias (only MAC address is displayed) is very long in my case (20+), making it difficult to select a device for pairing, especially since new devices are constantly being added and removed.
I installed blueman to see how it handles these devices, and it also does not display them.
Instead of ignoring all devices without an alias, I applied the filter only to unknown device types.
I also considered adding an option to enable/disable the filtering, but I'm not sure if it's really necessary or if anyone would actually use it.
=> improve(bluetooth): ignore devices with unknown type and without alias

cosmic-settings/src/pages/system/default_apps.rs, i18n/en/cosmic_settings.ftl
Implements https://github.com/pop-os/cosmic-settings/issues/900
=> feature: let users change default text editor

cosmic-settings/src/pages/desktop/window_management.rs, i18n/en/cosmic_settings.ftl
Relies on https://github.com/pop-os/cosmic-comp/pull/1189
~~Creates a new section in the "Window Managment" page called "Floating Layout", which has the "Window snap-to-edge threshold setting" that defaults to `0` (no edge snapping).~~
Adds a "Floating windows gravitate to nearby edges" toggle in the "Window Managment" page that sets the `edge_snap_threshold` cosmic-comp configuration to 10 pixels if enabled, or 0 pixels (off) if disabled.
=> Add window edge snapping setting

Cargo.lock, cosmic-settings/src/pages/system/default_apps.rs
**changes tl;dr**
- you can change your default terminal via COSMIC settings, but cosmic_settings_config is by default bound to `cosmic-term`
- when we change the default terminal, persist this setting if possible by grabbing the relevant `exec` from its FreeDesktop path
demonstration vid:
https://github.com/user-attachments/assets/2d7b0592-a440-422c-837f-7b4e75e5ed30
resolves https://github.com/pop-os/cosmic-epoch/issues/1557
=> Respect default terminal in cosmic_settings_config (keybind SUPER+T) when changed

cosmic-settings/src/pages/display/mod.rs, i18n/en/cosmic_settings.ftl
Designed like here https://github.com/pop-os/cosmic-settings/issues/924
This code isn't really ideal since I had to sync both slider and dropdown (and I'm still learning Rust :smile: ).
Also no gif/video since my OBS is acting up weird :shrug:
=> implement additional scale options

cosmic-settings/src/pages/power/backend/mod.rs
fixes #742 .
1. I have a detailed explanation on the issue
2. There is no specific icon for -charged so we use the -charging one which is the same
3. You can find the changed gnome like icons like this one here : https://github.com/ZorinOS/zorin-icon-themes/blob/38ffff902f67c8016b5fcb6654affb17f361ef28/ZorinBlue-Dark/scalable/status/battery-level-100-charged-symbolic.svg?plain=1
4. The code is conforming now to the gnome-shells from here:  https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/system.js#L76-L85
Visual of the issue:
=> fix(power): Fix battery charged icon when a device is fully charged.

cosmic-settings/src/pages/desktop/appearance/font_config.rs, cosmic-settings/src/pages/desktop/appearance/icon_themes.rs, cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/time/region.rs, cosmic-settings/src/widget/mod.rs
This prevents the checkmark from being clipped in the Font and Region selection drawers when resizing the window, and makes the icon theme selection buttons centered in the drawer.
Also includes some minor cleanup.
Fixes #895.
=> Prevent checkmark clipping

Cargo.lock, cosmic-settings/Cargo.toml
part of https://github.com/pop-os/freedesktop-desktop-entry/issues/41
draft until https://github.com/pop-os/cosmic-mime-apps/pull/1 merged
=> Bump freedesktop-desktop-entry to 0.7.8

cosmic-settings/src/pages/accessibility/magnifier.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/move_window.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/nav.rs, i18n/en/cosmic_settings.ftl
Should be merged after https://github.com/pop-os/cosmic-comp/pull/1251
=> Shortcut system changes for cosmic-comp#1005

cosmic-settings/src/pages/input/keyboard/mod.rs, i18n/en/cosmic_settings.ftl
This depends on pop-os/cosmic-comp#1220 landing first.
=> Add numlock configuration to keyboard page

cosmic-settings/src/pages/system/users/mod.rs
Fixes https://github.com/pop-os/cosmic-settings/issues/1045
=> fix: 'open' arrow icon on user details

cosmic-settings/src/app.rs, cosmic-settings/src/pages/mod.rs, cosmic-settings/src/pages/system/mod.rs, cosmic-settings/src/pages/system/startup_apps.rs, i18n/en/cosmic_settings.ftl
video preview:
https://github.com/user-attachments/assets/d2c63d92-26b7-4889-b4aa-d97b8f8bd0d5
**changes tl;dr**
- adds a new page 'Startup Applications' under System & Accounts
- this new page lists the user specific autostart applications (`~/.config/autostart`) and allows the user to add/remove entries (NB: ordering does not matter here)
- adding a new application symlinks the entry into your autostart directory - i chose this approach to make it a little more 'set and forget' / user friendly compared to hard copies
- removing an application unlinks / removes the file (dependent on whether its a full file or a symlink)
i'm happy with the functionality, but a few UX points that may need to be addressed:
- icon on System & Accounts page - unsure what would be better?
- dialog - needed at …
=> Adding in new functionality to select applications to start on login

cosmic-settings/src/pages/applications/default_apps.rs
fixes https://github.com/pop-os/cosmic-epoch/issues/1357
from discussions in mattermost, just adds `application/ogg` to the list of mime types used for the audio dropdown
=> adding application/ogg for mime types to load for audio dropdown

cosmic-settings/src/pages/applications/startup_apps.rs
**changes tl;dr**
- fallback to the `appid` (for name) and `application-default` (for icon) for desktop entries in the startup apps page (partial fix for https://github.com/pop-os/cosmic-settings/issues/1074 )
- removing any entry with `X-CosmicApplet` set from the search list, as per [this discussion on mattermost](https://chat.pop-os.org/pop-os/pl/ezo78g9kzifoieieyp1zugkito)
LHS - updated, RHS - current
=> adding fallback name/icon to desktop entries in startup apps, removing cosmic applets from search list

cosmic-settings/src/app.rs, cosmic-settings/src/pages/applications/startup_apps.rs, cosmic-settings/src/pages/desktop/panel/applets_inner.rs
This prevents the Add button in the Startup apps context drawer from wrapping, and increases the icon size to match the applet context drawer.
Also fixes the extra padding on the bottom of views, which pushed the scrollable up. Adds a bottom spacer to the scrollable content, to ensure that it doesn't touch the window edge at the bottom of a scroll.
=> [Startup apps] Improve styling

Cargo.lock, cosmic-settings/Cargo.toml, cosmic-settings/src/pages/system/users/mod.rs, i18n/en/cosmic_settings.ftl
Implementing the following from https://github.com/pop-os/cosmic-settings/issues/1127
- User creation and password update now requires double entry of matching passwords
- New flow for changing password from inline edit to separate dialog
- Password fields converted to secure_input with visibility toggles as per the greeter and network applet.
There is a separate issue of passwords never being set or updated correctly. This PR is no more or less broken than it is currently as it uses the same password update function https://github.com/pop-os/cosmic-settings/issues/844
Another existing issue with user settings that's not currently addressed in this PR is the updating of full name and username https://github.com/pop-os/cosmic-settings/issues/1128
=> feat: improved password workflow

cosmic-settings/src/pages/system/users/mod.rs
Relating to issue https://github.com/pop-os/cosmic-settings/issues/1044 - but also taking the chance to clear up a few bits.
- Individual user buttons were drawing on top of the container that had the standard rounded edges as other settings, so added some spacing at the top and bottom of that container
- General small tweaks of the layout to better match the [Figma](https://www.figma.com/design/Z6Z9Ox6WNkiiM8gcAkcElS/COSMIC-Settings-First-Release---Developer-Handoff?node-id=13918-2014&p=f)
- Added a placeholder for non pop-os distros that don't currently load the default profile image
- Added a fallback to show the username in the user list if there is no full name to show
=> fix: user list style and layout

cosmic-settings/src/pages/desktop/appearance/mod.rs
This will load the theme instead of just using light or dark defaults. Alternatively specific values from the theme config could be loaded but there are many values puled from the theme here.
=> fix(appearance): load theme for initial default

cosmic-settings/src/pages/desktop/wallpaper/config.rs, cosmic-settings/src/pages/desktop/wallpaper/mod.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs
**changes tl;dr**
- instead of using `/usr/share/backgrounds` everywhere, instead (try to) use the first `$XDG_DATA_DIRS` that has a `backgrounds` subdirectory
- if none, fallback to `/usr/share/backgrounds`
functionality remains unchanged on pop 24.04
=> iterate XDG_DATA_DIRS when loading backgrounds

cosmic-settings/src/pages/system/users/mod.rs, i18n/en/cosmic_settings.ftl
Addresses https://github.com/pop-os/cosmic-settings/issues/1172
It seems if a column isn't explicitly told a width it will let a child element (like the description text here) expand it into the space the other columns need.
=> fix: user admin toggle overflowing container

cosmic-settings/src/pages/system/users/mod.rs
Following on from PR https://github.com/pop-os/cosmic-settings/pull/1182 -  I didn't realise the same overflow was happening on the main user list as well as the new user dialog!
=> fix: apply the toggle overflow fix to the user list

cosmic-settings/src/pages/desktop/panel/inner.rs
Depends-on: https://github.com/pop-os/libcosmic/pull/880
Depends-on: https://github.com/pop-os/cosmic-panel/pull/396
All this involves is having a certain notch that the panel size slider is on when the panel is set to a custom size
=> Handle Custom panel size in cosmic-settings

cosmic-settings/src/pages/input/keyboard/mod.rs
=> fix: left alt behaviour when right alt set as alternate characters key

cosmic-settings/src/pages/desktop/wallpaper/mod.rs
fixes: #1187 &  #1251
Edit: Here's a [relevant Mattermost dicussion](https://chat.pop-os.org/pop-os/pl/n3gnei7fi38f8mq5udmgt3jqna):
dania
[last week]
I have a personnal wallpapper. I have found that with last cosmic-settings update when you go in desktop-apparence-wallpapers the actual wallpaper is automatically replaced by the first wallapper in the gallery and I have to reselect my personnal wallpapper.  I think the problem come from commit 0508323. Best regards Dania
16 replies
doods
[last week]
As-salamu alaykum,
When you say: "last cosmic-settings update", do you mean the last commit on the master branch, or the latest version in the repos of Pop!_OS? I don't see the issue in the master branch, but I can test the latest release if that's what you're using.
dania
[last week]
yes the …
=> fix(wallpaper): Settings reset on entering page

cosmic-settings/src/pages/desktop/appearance/mod.rs, cosmic-settings/src/pages/desktop/appearance/theme_manager.rs
Tested it locally and now the value gets persisted on both Dark & Light mode when the selection changes in the UI.
=> fix(appearance): Synchronize Roundness between dark & light mode

cosmic-settings/src/pages/networking/vpn/mod.rs, cosmic-settings/src/pages/networking/vpn/nmcli.rs
Adds a list of ciphers in priority order to use and fall back to. fixes #692
=> fix(vpn): set data ciphers

cosmic-settings/src/pages/desktop/appearance/font_config.rs
Some regular fonts that have slightly higher weights get filtered out due to the filter used in the font loading function being a little too intrusive.
Remove the condition for font weight to be regular so that all fonts will be available to be set for the interface/mono fonts.
Others like KDE, Gnome do not filter out fonts with higher weights since on the same system, other DEs allow the fonts to be selected. So there is need for Cosmic DE to filter out these fonts.
Fixes: https://github.com/pop-os/cosmic-settings/issues/859
=> fix(font): remove intrusive filter for fonts

cosmic-settings/src/pages/input/keyboard/shortcuts/common.rs, cosmic-settings/src/pages/input/keyboard/shortcuts/custom.rs
=> fix(shortcuts): ignore keyboard input when replace dialog is active

justfile
This fixes unrecognized option d errors on
freebsd utils.
This is unnecessary as \n is already a default limiter for Xargs and it breaks building with the BSD utils.
I tried to get this working with find -print0 and xargs -0 without any luck but given that there are no files with a space or newline in it's name (and that the current script would break anyways if there was one) I think this should be fine :)
=> Remove -d '\n' from xargs
